name: 'Build & Test'

on:
  push:
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run compile
    - run: npm run test
    - run: npm run package
    - name: Archive extension
      uses: actions/upload-artifact@v4
      with:
        name: vsconan.vsix
        path: vsconan-*.vsix
